feat(web): Add chip component
Jintus-live-projects/billard-training pull request #15
Opened 2022-10-04 23:07 UTC by Jagaimo380

closes #14

2022-10-04 23:28 UTC, Jagaimo380 commented
J'ai corrigé la pipeline chez moi mais je peux pas force push (j'ai amend sur le même commit). La branche semble protected, je sais pas d'où ça vient et je pense pas avoir les droits de changer ça.

2022-10-08 21:49 UTC, Jintus requested changes

2022-10-08 21:49 UTC, Jintus commented on web/src/components/Chip/Chip.test.tsx
> +})
Il faudrait de vrai TU, tu peux t'inspirer des TU que j'ai fait sur TopbarLink et Topbar

2022-10-08 21:49 UTC, Jintus commented on web/src/components/Chip/Chip.tsx
> +      {value}
Je ne suis pas certain de la nécessité de rajouter une notion de préfix. Vaut mieux laisser libre à l'appelant de savoir ce qu'il met dans la valeur et de faire de la concaténation si besoin e.g. value = '#aim'

2022-10-08 21:49 UTC, Jintus commented on web/src/components/Chip/Chip.tsx
> +      }`}
Pour éviter de surcharger le composant span, on pourrait extraire les classes conditionnées dans une constante avant et utiliser la constante ici. Ce serait plus lisible

2022-10-10 09:51 UTC, Jagaimo380 commented on web/src/components/Chip/Chip.tsx
> +      }`}
On constante interne au composant ou un truc plus global ?

2022-10-10 09:55 UTC, Jagaimo380 commented on web/src/components/Chip/Chip.tsx
> +      {value}
J'ai hésité mais je me suis dit que d'avoir un champ qui porte une notion de value ça serait mieux de que cette notion soit décorrélée de l'affichage. Par exemple si cette value est utilisée pour l'envoyer dans un appel back ou quoi ça peut être relou de devoir gérer le préfix.
D'autant plus que pour ce genre de composant je pense que ça peut être assez commun d'utiliser un préfix pour l'affichage.

2022-10-10 09:57 UTC, Jagaimo380 commented on web/src/components/Chip/Chip.test.tsx
> +})
Pour moi tu fais des tests d'intégration dans tes TU en faisant comme t'as fait.

2022-10-11 20:23 UTC, Jintus commented on web/src/components/Chip/Chip.tsx
> +      }`}
Une constante interne au composant c'est très bien pour le moment je pense

2022-10-11 20:26 UTC, Jintus commented on web/src/components/Chip/Chip.test.tsx
> +})
Oui je m'en suis rendu compte, j'ai du mal à mocker les lib externes, il faudrait que je me penche un peu plus sur le sujet. Tu y arrive toi ?

2022-10-11 20:28 UTC, Jintus commented on web/src/components/Chip/Chip.tsx
> +      {value}
Ok je vois ton point de vue. Il se vaut ! Ok pour le prefix. Il faudra sans doute le faire évoluer en React.Node au lieu de string plus tard, mais pour le moment, laissons comme ca.

2022-10-12 19:20 UTC, Jagaimo380 commented on web/src/components/Chip/Chip.test.tsx
> +})
Bah c'est surtout que mon composant est dumb. Donc si je fais pas de test d'integration, mes TU c'est jsute ce que j'ai fait

2022-10-12 19:21 UTC, Jagaimo380 commented on web/src/components/Chip/Chip.tsx
> +      }`}
Tu veux que je change du coup ?

2022-10-12 19:31 UTC, Jintus requested changes

2022-10-12 19:31 UTC, Jintus commented on web/src/components/Chip/Chip.test.tsx
> +})
Comme vu ensemble en stream, ce serait bien que on test au moins la présence des class en mode isActive. Et pourquoi pas, la présence de la valeur passé dans le rendu final

2022-10-12 19:31 UTC, Jintus commented on web/src/components/Chip/Chip.tsx
> +      }`}
Yes

2022-10-12 22:27 UTC, Jagaimo380 commented on web/src/components/Chip/Chip.test.tsx
> +})
J'ai complété les TU

2022-10-12 22:28 UTC, Jagaimo380 commented on web/src/components/Chip/Chip.tsx
> +      {value}
J'ai modifié pour mettre le prefix dans un child avec un ReactNode

2022-10-13 19:43 UTC, Jintus approved these changes

2022-10-13 19:45 UTC, merged