style: update tailwind color scheme
Jintus-live-projects/billard-training pull request #30
Opened 2022-10-27 21:35 UTC by Alexandreblnqro

2022-10-28 06:08 UTC, Alexandreblnqro commented
Je viens d'observer sur le Figma en m'occupant de la régression que certaines couleurs utilisée, comme le violet de ce que je présume être le Chip était pas prise en compte dans les styles de couleurs Figma à droite.
![image](https://user-images.githubusercontent.com/71755937/198515014-bc10e078-12b0-4203-b6d5-8dcba950323f.png)
Je vais m'occuper de les ajouter dans la config TailWind mais je pense que ça serait bien d'afficher toutes les couleurs crée directement dans les couleurs à droite. Comme ça je pourrais regarder de temps en temps et mettre à jour selon les besoins.

2022-10-28 21:35 UTC, Jintus requested changes
Quelques oublies dans les couleurs que tu as supprimé. Elle était toujours utilisée.

2022-10-28 21:35 UTC, Jintus commented on web/src/components/Trainings/Sidebar/TrainingsSidebar/TrainingsSidebar.tsx
> +    <nav className="h-full bg-gray-secondary p-2">
Il y a un soucis avec cette classe. La couleur n'existe pas il me semble `gray-secondary`. De plus la couleur tu l'as supprimé du coups sans la déplacer autre part. Il faudrait lui trouver un nom. white-gray ??

2022-10-28 21:35 UTC, Jintus commented on web/config/tailwind.config.js
> -          light: '#D1D1D1',
Cette couleur à disparue c'est celle du loader il me semble. Il faudrait la mettre qqp genre DEFAULT

2022-10-28 21:35 UTC, Jintus commented on web/src/components/Loader/Loader.tsx
> +  return <div className={`animate-pulse bg-gray-active ${className}`}></div>
Ce n'est pas la bonne couleur du coups

2022-10-28 21:37 UTC, Jintus commented
> Je viens d'observer sur le Figma en m'occupant de la régression que certaines couleurs utilisée, comme le violet de ce que je présume être le Chip était pas prise en compte dans les styles de couleurs Figma à droite.
> 
> ![image](https://user-images.githubusercontent.com/71755937/198515014-bc10e078-12b0-4203-b6d5-8dcba950323f.png)
> 
> Je vais m'occuper de les ajouter dans la config TailWind mais je pense que ça serait bien d'afficher toutes les couleurs crée directement dans les couleurs à droite. Comme ça je pourrais regarder de temps en temps et mettre à jour selon les besoins.
> 
> 

Oui je suis d'accord, je vais refaire une passe dans le Figma pour référencer les couleurs oubliées.

2022-10-29 08:11 UTC, Jintus approved these changes
Seems good to me

2022-10-29 08:14 UTC, merged